=== SeismicData/SEIS-PROV/definitions/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://seisprov.org/internal_type_def",
  "type": "object",
  "properties": {
    "package": {
      "id": "http://seisprov.org/internal_type_def/package",
      "type": "string",
      "enum": ["seis_prov"]
    },
    "type": {
      "id": "http://seisprov.org/internal_type_def/type",
      "type": "string",
      "enum": ["entity", "activity"]
    },
    "name": {
      "id": "http://seisprov.org/internal_type_def/name",
      "type": "string",
      "pattern": "[a-z_]{4,}"
    },
    "two_letter_code": {
      "id": "http://seisprov.org/internal_type_def/two_letter_code",
      "type": "string",
      "pattern": "^[a-z]{2}$"
    },
    "recommended_label": {
      "id": "http://seisprov.org/internal_type_def/recommended_label",
      "type": "string",
      "pattern": "^[a-zA-Z ]{4,}$"
    },
    "description": {
      "id": "http://seisprov.org/internal_type_def/description",
      "type": "string"
    },
    "attributes": {
      "id": "http://seisprov.org/internal_type_def/attributes",
      "type": "array",
      "items": {
        "id": "http://seisprov.org/internal_type_def/attributes/0",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "id": "http://seisprov.org/internal_type_def/attributes/name",
            "type": "string",
            "pattern": "^[a-z_]+"
          },
          "type": {
            "id": "http://seisprov.org/internal_type_def/attributes/type",
            "type": "string",
            "enum": ["xsd:string", "xsd:byte", "xsd:decimal", "xsd:int",
                     "xsd:integer", "xsd:long", "xsd:negativeInteger",
                     "xsd:nonNegativeInteger", "xsd:nonPositiveInteger",
                     "xsd:positiveInteger", "xsd:short", "xsd:unsignedLong",
                     "xsd:unsignedInt", "xsd:unsignedShort",
                     "xsd:unsignedByte", "xsd:date", "xsd:dateTime",
                     "xsd:duration", "xsd:gDay", "xsd:gMonth", "xsd:gMonthDay",
                     "xsd:gYear", "xsd:gYearMonth", "xsd:time", "xsd:anyURI",
                     "xsd:base64Binary", "xsd:boolean", "xsd:double",
                     "xsd:float", "xsd:hexBinary"]
          },
          "pattern": {
            "id": "http://seisprov.org/internal_type_def/attributes/pattern",
            "type": "string"
          },
          "description": {
            "id": "http://seisprov.org/internal_type_def/attributes/description",
            "type": "string"
          },
          "required": {
            "id": "http://seisprov.org/internal_type_def/attributes/required",
            "type": "boolean"
          },
          "example_value": {
            "id": "http://seisprov.org/internal_type_def/attributes/example_value"
          }
        },
        "required": ["name", "type", "description", "required", "example_value"]
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "package",
    "type",
    "name",
    "two_letter_code",
    "recommended_label",
    "description",
    "attributes"
  ]
}

=== SeismicData/SEIS-PROV/definitions/activities/detrend.json
{
    "package": "seis_prov",
    "type": "activity",
    "name": "detrend",
    "two_letter_code": "dt",
    "recommended_label": "Detrend",
    "description": "Remove trend from the data.",
    "attributes": [
        {
            "name": "detrending method",
            "type": "xsd:string",
            "description": "The method used to remove the trend from the data.",
            "required": true,
            "example_value": "demean"
        }
    ]
}

=== SeismicData/SEIS-PROV/definitions/activities/decimate.json
{
    "package": "seis_prov",
    "type": "activity",
    "name": "decimate",
    "two_letter_code": "dc",
    "recommended_label": "Decimate",
    "description": "Downsample the waveform data by an integer factor. Any applied anti-alias filtering has to be described by a filtering activity.",
    "attributes": [
        {
            "name": "factor",
            "type": "xsd:positiveInteger",
            "description": "The decimation factor",
            "required": true,
            "example_value": 5
        }
    ]
}

=== SeismicData/SEIS-PROV/definitions/entities/waveform_trace.json
{
    "package": "seis_prov",
    "type": "entity",
    "name": "waveform_trace",
    "two_letter_code": "wf",
    "recommended_label": "Waveform Trace",
    "description": "Represents a continuous, equally sampled observed or synthetic waveform trace. Most attributes are optional and can be used to describe either very detailed or fairly general provenance information.",
    "attributes": [
        {
            "name": "seed_id",
            "type": "xsd:string",
            "pattern": "^[A-Z]{1,2}\\.[A-Z]{1,5}\\.[A-Z]{0,2}\\.[A-Z]{1,3}$",
            "description": "The SEED id of the recording station.",
            "required": false,
            "example_value": "BW.FURT..EHZ"
        },
        {
            "name": "start_time",
            "type": "xsd:dateTime",
            "description": "The time of the first sample in UTC.",
            "required": false,
            "example_value": "2012-04-23T18:25:43.511Z"
        },
        {
            "name": "number_of_samples",
            "type": "xsd:positiveInteger",
            "description": "The number of samples in the waveform trace.",
            "required": false,
            "example_value": 10000
        },
        {
            "name": "sampling_rate",
            "type": "xsd:double",
            "description": "The sampling rate of the data.",
            "required": false,
            "example_value": 20.0
        },
        {
            "name": "units",
            "type": "xsd:string",
            "description": "Units of the waveform data in a common abbreviation, e.g. `m`, `m/s`, `nm/s^2`, ...",
            "required": false,
            "example_value": "m/s"
        }
    ]
}

=== SeismicData/SEIS-PROV/definitions/activities/interpolate.json
{
    "package": "seis_prov",
    "type": "activity",
    "name": "interpolate",
    "two_letter_code": "ip",
    "recommended_label": "Interpolate",
    "description": "Interpolate the data to new sampling points.",
    "attributes": [
        {
            "name": "interpolation_method",
            "type": "xsd:string",
            "description": "The method used to interpolate the samples.",
            "required": true,
            "example_value": "cubic spline"
        },
        {
            "name": "new_start_time",
            "type": "xsd:dateTime",
            "description": "The time of the first sample in UTC after the interpolation.",
            "required": false,
            "example_value": "2012-04-23T18:25:43.511Z"
        },
        {
            "name": "new_number_of_samples",
            "type": "xsd:positiveInteger",
            "description": "The number of samples after the interpolation.",
            "required": false,
            "example_value": 5000
        },
        {
            "name": "new_sampling_rate",
            "type": "xsd:double",
            "description": "The sampling rate after the interpolation.",
            "required": true,
            "example_value": 10.0
        }
    ]
}

=== SeismicData/SEIS-PROV/definitions/activities/waveform_simulation.json
{
    "package": "seis_prov",
    "type": "activity",
    "name": "waveform_simulation",
    "two_letter_code": "ws",
    "recommended_label": "Waveform Simulation",
    "description": "Generate data by running some numerical or analytic code. Must be associated with one or more agents and use some entities to achieve a useful description.",
    "attributes": [
    ]
}

=== SeismicData/SEIS-PROV/definitions/activities/rotate.json
{
    "package": "seis_prov",
    "type": "activity",
    "name": "rotate",
    "two_letter_code": "rt",
    "recommended_label": "Rotate",
    "description": "Rotate multi-component data. This activity has no other attributes. The rotation angles are described by input and output activities.",
    "attributes": [
    ]
}

=== SeismicData/SEIS-PROV/definitions/activities/differentiate.json
{
    "package": "seis_prov",
    "type": "activity",
    "name": "differentiate",
    "two_letter_code": "df",
    "recommended_label": "Differentiate",
    "description": "Differentiate the data with respect to time.",
    "attributes": [
        {
            "name": "order",
            "type": "xsd:positiveInteger",
            "description": "The order of the derivative, e.g. the nth derivative.",
            "required": true,
            "example_value": 1
        },
        {
            "name": "differentiation_method",
            "type": "xsd:string",
            "description": "The differentiation method.",
            "required": false,
            "example_value": "three point centered differences"
        },
        {
            "name": "input_units",
            "type": "xsd:string",
            "description": "Units of the input data in a common abbreviation, e.g. `m`, `m/s`, `nm/s^2`, ...",
            "required": false,
            "example_value": "m"
        },
        {
            "name": "output_units",
            "type": "xsd:string",
            "description": "Units of the output data in a common abbreviation, e.g. `m`, `m/s`, `nm/s^2`, ...",
            "required": false,
            "example_value": "m/s"
        }
    ]
}

=== SeismicData/SEIS-PROV/definitions/activities/resample.json
{
    "package": "seis_prov",
    "type": "activity",
    "name": "resample",
    "two_letter_code": "rs",
    "recommended_label": "Resample",
    "description": "Resample the data in the frequency domain.",
    "attributes": [
        {
            "name": "frequency_domain_window",
            "type": "xsd:string",
            "description": "The window applied to the signal in the Fourier domain.",
            "required": false,
            "example_value": "Hanning"
        },
        {
            "name": "new_start_time",
            "type": "xsd:dateTime",
            "description": "The time of the first sample in UTC after the interpolation.",
            "required": false,
            "example_value": "2012-04-23T18:25:43.511Z"
        },
        {
            "name": "new_number_of_samples",
            "type": "xsd:positiveInteger",
            "description": "The number of samples after the interpolation.",
            "required": false,
            "example_value": 5000
        },
        {
            "name": "new_sampling_rate",
            "type": "xsd:double",
            "description": "The sampling rate after the interpolation.",
            "required": true,
            "example_value": 10.0
        }
    ]
}
